version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glpi-sql.rule=Host(`localhost`)"
      - "traefik.http.services.glpi-sql.loadbalancer.server.port=5000"

networks:
  app-network:
    name: gerador_sql_glpi10_default
    external: true
